In [2]:
import numpy as np

In [6]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones(2)

array([1., 1.])

In [12]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand(5)

array([0.10240488, 0.53347598, 0.82416578, 0.32511343, 0.9734914 ])

In [16]:
np.random.rand(5,5)

array([[0.22929434, 0.14367449, 0.97100998, 0.87975787, 0.62283112],
       [0.27239359, 0.32682569, 0.68707167, 0.74189945, 0.21379546],
       [0.92936415, 0.18140008, 0.7591334 , 0.81093982, 0.311981  ],
       [0.29513605, 0.14260005, 0.15033946, 0.71572971, 0.09566775],
       [0.71225818, 0.42805246, 0.33442562, 0.34867662, 0.0914229 ]])

In [29]:
arr = np.arange(25)

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

__Numpy array indexing__

In [31]:
arr = np.arange(0,11)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr[8]

8

In [37]:
arr[1:5]

array([1, 2, 3, 4])

In [38]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [42]:
arr[0:4]

array([0, 1, 2, 3])

In [43]:
arr[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr_copy = arr.copy()

In [45]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr_2d = np.array([[1,2,3], [4,5,6],[7,8,9]])

In [47]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
arr_2d[1,2]

6

In [51]:
arr_2d > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

__NumPy Operation__

In [53]:
arr = np.arange(0,11)

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [56]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [57]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [58]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [59]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [60]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [61]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [62]:
np.max(arr)

10

In [63]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [64]:
np.log(arr)

C:\Users\DELL\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [68]:
arr = np.arange(9)
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])